### ISSUE TITLE
Add to TIC80 wiki tools

### ISSUE THREAD

**Issue by Skeptim** [wojciech-graj/TIC-MIDI#1]
Hi!
That's a great tool! Thanks!
I just wanted to suggest you to add it to the TIC80 wiki as an external tool or something https://github.com/nesbox/TIC-80/wiki/tools
I can do it for you if you prefer.
Thanks in advance

**Comment by wojciech-graj** [comment]
Hey, I didn't know about the existence of that tools list, so thanks for telling me. I added TIC-MIDI to it.
